"""add paid_at to payments

Revision ID: 86316c832e62
Revises: 1c54cd13301c
Create Date: 2026-10-02 17:32:07.423084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86316c832e62'
down_revision: Union[str, Sequence[str], None] = '1c54cd13301c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'paid_at')
    # ### end Alembic commands ###
